### ISSUE TITLE
Add traceroute action

### ISSUE THREAD

**Issue by jjm** [StackStorm-Exchange/stackstorm-networking_utils#15]
Add a action to run traceroute from stackstorm to a remote system, should also support chatops alias.

**Comment by jjm** [comment]
It's been a year, don't think I'll have time to do this.

**Comment by kedare** [comment]
There is already a `traceroute_mtr` action, are you missing any feature on it ?

**Comment by jjm** [comment]
@kedare This issue pre-dates your PR (#17) that added `traceroute_mtr` by about 6 months. I was planning on doing something similar to what we had in our internal pack at Pulsant when I first created this pack.

Maybe this should have been closed at the time, I'll just do that now.

**Comment by kedare** [comment]
Great, happy to see that my PR fit your need :)
